### ISSUE TITLE
problem with poweroff-commit

### ISSUE THREAD

**Issue by MyLive** [frank-w/BPI-Router-Linux#35]
Hi Frank,

if the Powerbutton bypassed ( bridged ), the system reboot´s the whole time :-(.

Best regards,
René

**Comment by frank-w** [comment]
How far goes the boot-process? As far as i know is the power-key not detected after bootup. It is/was only used to get initial bootup

**Comment by MyLive** [comment]
after rc.local / starting services the system restarts ...

**Comment by frank-w** [comment]
You have tried without this commit? To be sure problem is really this one.

Strange that reboot happens after system is nearly up

**Comment by MyLive** [comment]
Yes and it works ...
i added the line "blacklist mtk_pmic_keys" to /etc/modprobe.d/pmics_key.conf
now the Module is not loaded an the Power Key ignored but is not a "good" solution :-)

**Comment by MyLive** [comment]
i have veryfied on my "main" system. Without blacklist, it reboots all the time, after module blacklist, it works fine :-)

**Comment by frank-w** [comment]
Seems that pressing the powerkey in running system now it triggers poweroff

**Comment by frank-w** [comment]
link to the commit: https://github.com/frank-w/BPI-R2-4.14/commit/fc6285a3f9bde6c7bb32c4f79675d696ff2667d3

**Comment by kgara** [comment]
Sorry for some retro-posting. But I am a little bit confused. So what is the current status of this problem? Is there a way to get both "power up after power outage" + "working shutdown by power button press"? Or I should choose only one :) (definitely first for me) and just solder the power button pins and blacklist mtk_pmic_keys to avoid bootloops? Tried to analyze that commit - it is huge - so it just enables power button for those who has no soldering and does not want "power up after power outage"?

**Comment by leopucci** [comment]
If this is a router board, it is expected that if my house electricity goes down, when it came back, the router should auto start again, as any other wifi/router device. 
Don't you agree?
This should be the standard, not the workaround. 
Will be any definitive solution about this that does not involve disabling acpi? (or acpi should be disabled by default i think, so we could upgrade without trouble).

**Comment by frank-w** [comment]
@MyLive can you reproduce this: http://forum.banana-pi.org/t/bpi-r2-boot-power-suppy/3647/79?
