### ISSUE TITLE
[internal wifi] AP not visible if hostapd killed first time

### ISSUE THREAD

**Issue by frank-w** [frank-w/BPI-Router-Linux#4]
hostapd is working the first-time, after killing it and restart, AP is not visible on clients (no error-Message on hostapd). tested on debian jessie (after upgrade to stretch it have same behavior after killing hostapd)

**Comment by frank-w** [comment]
AP can be started after killing if the WMT-Device is resetted via

    echo 0 >/dev/wmtWifi
    echo A >/dev/wmtWifi

**Comment by BGFWDev** [comment]
Frank, is there another method to contact you offline about this project?

**Comment by frank-w** [comment]
https://github.com/frank-w

http://forum.banana-pi.org/c/Banana-Pi-BPI-R2
